version: "3.4"

services:
  database:
    build:
      context: .
      target: postgresDB
    env_file:
      .env
    ports:
      - "5432:5432"
    stdin_open: true
    networks:
      - project

networks:
  project:
    external: true
