version: "3.4"

services:
  database:
    build:
      context: .
      target: postgresDB
    stdin_open: true


  adminer:
    build:
      context: .
      target: adminer
    depends_on:
      - database
    restart: unless-stopped
    stdin_open: true


networks:
  project:
    external: true